### ISSUE TITLE
UXTools and ARSessionConfig breaks when HTC Vive is connected

### ISSUE THREAD

**Issue by andnovar** [microsoft/MixedReality-UXTools-Unreal#11]
When the HTC Vive is plugged in the computer, the engine seems not to import the AR plugin, which produces a wrong behavior on the hands interactions and camera navigation as can be seen in video.

https://youtu.be/I3RsBQXWFpM 

I am using Unreal 4.25.3 , UXTools 0.9.0 and SteamVR 1.13.10

**Comment by lukastoenneMS** [comment]
I couldn't test this specific setup due to lack of HTC Vive availability, but i'm pretty sure this is some ambiguity on the Unreal engine side. The Steam XRSystem is enabled by default, so connecting a Vive will enable that XRSystem and override the WindowsMixedReality one, so interactions stop working.

The simulated hands still show up because UXT input simulation doesn't properly check the type of the active XRSystem. I've logged this issue separately. It's an inconvenience but doesn't have much of a bearing on the main problem, which is that priority of the XRSystem is pretty much hardcoded.

I'm afraid we can't do much about this on the UXTools side.

**Comment by lukastoenneMS** [comment]
I'm closing this bug, since it's not really an issue with UXTools but rather the HMD priority in UE4. The solution suggested by @makeshiftdan is what I would recommend when dealing with multiple HMDs attached.

Also note that with the 0.12 release of UXTools the input simulation is no longer part of the WMR plugin, so it might work a bit better out of the box (untested).
