### ISSUE TITLE
Far interactions beam origin is wrong (using UXTools v0.10.0)

### ISSUE THREAD

**Issue by xTeufelx** [microsoft/MixedReality-UXTools-Unreal#17]
I recently worked through the [Unreal development journey tutorial series](https://docs.microsoft.com/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch1), using UE 4.25.4 and UXTools v0.10.0. Everything was fine, until I deployed my application on a real device. The origin of the far interactions beam was not, as expected, within my hand. Instead, both beams for left and right hands were coming out of my head. I was still able to control the beams with my hands, just the origin was wrong. Since I am developing with Unreal for the first time, it could be that I did something wrong, so I repeated the tutorial except that i left out the chess aspects and went straight for the interaction stuff. Same result. As I said, I am new to Unreal development, so I don't know how to try and fix this problem. The only thing I tested was to repeat the tutorial once again, but now using UXTools v0.9.0, where the beam origin of the far interactions was in my hands as expected. Seems to be a problem with UXTools v0.10.0. Do you have any suggestions how I can possibly fix it?

[ChessApp.zip](https://github.com/microsoft/MixedReality-UXTools-Unreal/files/5546265/ChessApp.zip)

![MRPawns Event Graph](https://user-images.githubusercontent.com/23343850/99254274-67be9e00-2812-11eb-8b41-edccd242b475.png)

![MRPawns Component hierarchy](https://user-images.githubusercontent.com/23343850/99254369-8f156b00-2812-11eb-8b3d-16ac6f0b0a30.png)

**Comment by jjimenezg93** [comment]
Hi @xTeufelx,

Thank you for your report! There are a couple of things that could help in resolving this faster:

1.  Could you attach a .zip file of your project? Please remember to delete the `Binaries` and `Intermediate` folders to reduce the file size.
2. Otherwise, could you please add a screenshot of your [`UxtHandInteractionActor`'s setup][1]? Both Blueprint nodes and component's hierarchy.

I'm assuming that there's a typo and you're using **UE 4.25.4**.


[1]: https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch4#spawning-hand-interaction-actors

**Comment by xTeufelx** [comment]
I updated the ticket according to your request. Did I capture the correct areas? Please note that I deleted the folders `Plugins` and `Build` as well in order to reduce the size of the .zip file so that it can be uploaded. 

Yes, your assumtion was correct. I corrected the typo.

**Comment by jjimenezg93** [comment]
Great, thank you!

I was able to reproduce the behaviour you described, so I'll investigate and come back to you once I find out what's going on.

Sorry for the inconvenience.

**Comment by jjimenezg93** [comment]
Hi again @xTeufelx,

You should be able to solve your issue by re-attaching the `Camera` component to the root `CollisionComponent` directly, instead of having it attached to the `MeshComponent`:

![reattach_component](https://user-images.githubusercontent.com/6595611/99278576-21c00500-2827-11eb-9042-c197201e2b75.gif)

If that doesn't work, please do not hesitate to reopen this issue!

I appreciate that this step of the [Unreal development journey][1] might be ambiguous, so we'll work on improving it.

Thank you very much for your report and sorry for the inconvenience!

[1]: https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch3#create-a-pawn

**Comment by xTeufelx** [comment]
Hello @jjimenezg93,

I will implement and try you solution tomorrow.
 Thank you very much for your quick responses and for helping me out with this.
