### ISSUE TITLE
HandMenu Error and DestructibleActor

### ISSUE THREAD

**Issue by Eddiechui** [microsoft/MixedReality-UXTools-Unreal#24]
Hi! I have two questions. 

1st question: 
I designed a level with HandMenu with several child actors linking with buttons. I also have the same HandMenu on the next level. It worked great when I was playing in the unreal engine. I packaged the game and imported it into my Hololens 2 and here came the problem. 

In the first level, I turned my palm up and the hand menu popped out and functioned normally. All the buttons were put in order as I designed. But when I went to the next level (by clicking the 'next level' button), the hand menu was still there but all the buttons were disordered/ disappeared. I was wondering if you had the same problem when viewing with Hololens2.

2nd question:
This question may not be related to the UXTools but it is related to the Hololens. I found that the DestructibleActor of the Unreal Engine could not be viewed in the Hololens. Is this really the fact?

Thanks!

**Comment by lukastoenneMS** [comment]
I've made a repro project from scratch to test this, using the 0.11 UXT release. If you have a repro project you can share that might help identify the problem too.
[https://github.com/lukastoenneMS/UxtHandMenuTest](https://github.com/lukastoenneMS/UxtHandMenuTest)

Can you be more specific about the disordered buttons? Some screenshots might help with this. Maybe have a look at the project above and see if this is the way you created the menu or if there is some difference.

I'm not seeing buttons moving relative to the menu. But the buttons and hand menu have some questionable behavior that might be causing this:
When the button is loading a new map on the "Pressed" event, and the loaded map has a similar button in the same place, it can cause an infinite loop. The loaded map's menu button is immediate pressed when it appears under the user's finger, so map A loads map B loads map A, ad infinitum. This could be avoided in a number of ways:
- Use the "Released" event instead of "Pressed" so the user has to move their finger to trigger the map load.
- UXTools could provide a "ForceConstraint" function on the UxtHandConstraint component (PalmUpConstraint subclass here), so the menu does not push itself into the user's finger when moving to a new player location. Currently the menu always spawns at its set location and then jumps towards the player.

Am i assuming correctly that the DestructibleActor is part of the Apex Destruction plugin? I have no experience with that, but will try to repro the issue.

**Comment by Eddiechui** [comment]
Oh yes! I think you are correct. It should be the problem of the infinite loop of the pressed event. I do not have the Hololens2 with me now. I will try the 'Released' event instead and also take some screenshots of disordered buttons when I get back my Hololens. Thanks!

Yes, the DestructibleActor is part of the Apex Destruction plugin. Hope that it is only my problem instead of the system's. Or else I have to figure out another way to do it haha.

**Comment by Eddiechui** [comment]
I tried the 'Released' event but still encountered the same problem. You can find the attached images for your information.
![1  FirstLevel](https://user-images.githubusercontent.com/59867565/109281581-74ae4d00-7857-11eb-95c9-e1cb47f86365.JPG)
![2  NextLevel_ButtonDisappear](https://user-images.githubusercontent.com/59867565/109281588-76781080-7857-11eb-99ee-05e0fa87ffdf.JPG)
![3  NextLevel_ButtonDisordered](https://user-images.githubusercontent.com/59867565/109281589-76781080-7857-11eb-9f8a-0e4d488a173d.JPG)

Sorry that I do not understand the "ForceConstraint" function... can you make a screenshot of it? Thanks.

**Comment by lukastoenneMS** [comment]
This "force constraint" function does not exist yet, we'd have to add that to the component API. Calling it would instantly move the menu to a position where the constraint is satisfied, so it doesn't move any more as long as the user stays still. That would be useful for cases like map loading or teleporting where you don't want the menu to jump across the room.

From looking at the pictures my first guess would be some kind of scaling issue. You also seem to have multiple backplate components. I can't really tell what is going on without a repro case, sorry. Try to keep the hierarchies as flat as possible, with the backplate and mesh components directly parented to the button component. Is it possible that you copy-pasted the buttons and they got parented to each other?

**Comment by lukastoenneMS** [comment]
I'm closing this issue, assuming that using the "Release" event solved it.
