### ISSUE TITLE
Surface highlighting on BoundsControls not working

### ISSUE THREAD

**Issue by SuperFreqA** [microsoft/MixedReality-UXTools-Unreal#25]
**Using version 0.11
UE Version 4.26.1
plugin loaded in project directory (not sure if that matters.**

The default Uxt Bounds Control Component does not appear to have the proximity surface highlighting I am used to for HL2 controls. Is there a way to turn this on. Corner and edge controls display correctly but surfaces between them don't have that "flashlight" highlighting.

**Comment by jjimenezg93** [comment]
Hi @SuperFreqA,

Thanks for your report!

I understand that you're missing this highlighting:

![proximity_surface](https://user-images.githubusercontent.com/6595611/109174375-b3bba000-777c-11eb-824d-6aff934c154a.png)

I'm assuming that you aren't observing the issue in our demo scene, is that right? If so, could you please provide a `.zip` file with a project where this problem reproduces? Please remember to delete the `Binaries/` and `Intermediate/` folders to shrink the size of the file.

If that wasn't possible, could you please provide more details about how the actor with the `UxtBoundsControlComponent` is set up?

Thank you!

**Comment by EqipInc** [comment]
Unfortunately this is a project I can't share (company policy). I can probably try to reproduce the issue with another project.
The actor is setup with two meshes under the scene node along with some proprietary deformable mesh components to do free form deformation. The UxtBoundsControl  and UxtGenericManipulator are components at the root. ![MicrosoftTeams-image](https://user-images.githubusercontent.com/39603270/109217796-86b6bf80-7773-11eb-94f4-49308dc7734b.png)
Most stuff is just still set to default values.
We had initially been using the 0.10 version (or whatever the first 4.26 release was) and updated manually as  a project level plug-in.

**Comment by SuperFreqA** [comment]
Unfortunately this is a project I can't share (company policy). I can probably try to reproduce the issue with another project.
The actor is setup with two meshes under the scene node along with some proprietary deformable mesh components to do free form deformation. The UxtBoundsControl  and UxtGenericManipulator are components at the root.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/19316049/109218868-312ee280-7774-11eb-96c5-f8d8eba71f3c.png)

Most stuff is just still set to default values.
We had initially been using the 0.10 version (or whatever the first 4.26 release was) and updated manually as  a project level plug-in.

**Comment by jjimenezg93** [comment]
In order to get that highlighting behaviour, our default `BP_CoffeeCup` has a mesh component called `BoundControl` with `SM_BoundsControl` as static mesh and `MI_BoundsControl` as material instance, which dynamically render the highlight when appropriate.

Judging by the names of the components in your example, I think you might be missing this `StaticMesh` component. Is that the case? If so, you can copy it from the `BP_CoffeeCup` (note that the `Construction Script` also includes the BP code to automatically scale it).

Could you please let us know if this solves your issue?

Thanks!

**Comment by EqipInc** [comment]
Where can I get this BP_CoffeeCup? is there a demo project that I could reference for this?

**Comment by SuperFreqA** [comment]
Where can I get this BP_CoffeeCup? is there a demo project that I could reference for this?

**Comment by SuperFreqA** [comment]
This does seem to fix the problem mostly. I did need to add the BoundControl object and the extra variables DefaultActorTransform and ShowBoundControl along with the construction script. 
Unfortunately getting the bounds for the two static mesh objects I have does not match the bounds for the UxtBoundsControl object. Our meshes have an origin outside of the object which is accounted for in the uxtBoundsControl but not when "get component bounds" is called in the blueprint. So we get a BoundControl object that is smaller than the uxtBoundsControl object. 
I assume that uxtBoundsControl is using a different call to set the box size?

**Comment by jjimenezg93** [comment]
Indeed, the `UxtBoundsControlComponent` automatically adds a `BoxCollider`, which we use to prevent pointers from passing through the box and matches the transforms of the handles.

My understanding of your current problem is that this `BoxCollider` doesn't match the `BoundControl` mesh added in the Blueprint:

![image](https://user-images.githubusercontent.com/6595611/109787078-c19e7480-7c05-11eb-95f0-9d11f7738a2c.png)

We have a task in our backlog to fix this and create both of them automatically, but I'm afraid that we don't know yet if it's going to make it into the next release.

In the meantime, you could work around this.

The logic used internally basically iterates through all the `UPrimitiveComponent` inside the actor (starting from the `RootComponent`) and creates an `FBox` that surrounds all of them. This changes slightly in `0.12.0`, because we modified the API ([Release Notes entry][2] and [code][3]) and added a [`BoundsOverride` property][1] which allows you to start the search on one specific `USceneComponent`, instead of the root.

Therefore, you can try to replicate the code inside `UUxtMathUtilsFunctionLibrary::CalculateNestedBoundsInGivenSpace` in the Blueprint, ignoring the `BoundControl` itself. You could also try to modify our API by adding the `UFUNCTION(BlueprintPure, Category = "UXTools|Math Utils")` annotation to that function, so it can be called from the Blueprint. However, there'd be a conflict once you upgrade to `0.12.0`, as we have modified the parameters of that function.

Do you think any of those workarounds would work for you? Happy to help further if necessary.

[1]: https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/63b22b93fb943281e9782826fcf280e0e248c7d9/Docs/ReleaseNotes.md#boundsoverride-property-in-uxtboundscontrol
[2]: https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/63b22b93fb943281e9782826fcf280e0e248c7d9/Docs/ReleaseNotes.md#uxtmathutilsfunctionlibrarys-api-update
[3]: https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/63b22b93fb943281e9782826fcf280e0e248c7d9/UXToolsGame/Plugins/UXTools/Source/UXTools/Private/Utils/UxtMathUtilsFunctionLibrary.cpp#L76

**Comment by SuperFreqA** [comment]
This works. Thank you for your help.

**Comment by SuperFreqA** [comment]
![Screenshot 2021-03-18 095255](https://user-images.githubusercontent.com/19316049/111656256-f991e400-87cf-11eb-9795-56fb97ef216a.png)
Here was my setup for those that have this issue.
I am still seeing some artifacts with this solution that include proximity detection for grabbing corners and sides seems to be off by an inch or two. Also I am not getting triggers on translation (grabbing center of volume) with the flags turned on. Also the surface highlight (blue dot) will sometimes remain on the control after hands are moved away.

I am wondering if there were some issues going from 0.10 to 0.11? One of our UxtGenericManipulators was completely blank of details in the blueprint that was using it. We needed to delete it and replace it.
