### ISSUE TITLE
FindFarTarget() has to check owner before For-Loop.

### ISSUE THREAD

**Issue by crssnky** [microsoft/MixedReality-UXTools-Unreal#27]
UxtFarPointerComponent.cpp
```C++
// Finds the far target a primitive belongs to, if any
static UObject* FindFarTarget(UPrimitiveComponent* Primitive)
{
	if (Primitive)
	{
		for (UActorComponent* Component : Primitive->GetOwner()->GetComponents())  // <-- No check "owner==nullptr"
		{
			if (Component->Implements<UUxtFarTarget>() && IUxtFarTarget::Execute_IsFarFocusable(Component, Primitive))
			{
				return Component;
			}
		}
	}

	return nullptr;
}
```

I use GeometryBrush actors in PIE.
UE4 crashes in `FindFarTarget()` when FarPointer touches a GeometryBrush actor.
GeometryBrush actors does not have owner.
It has to check owner before For-Loop.

Maybe, there are others like this.

**Comment by lukastoenneMS** [comment]
Thanks for reporting! This is fixed in the master branch now ([link to commit](https://github.com/microsoft/MixedReality-UXTools-Unreal/commit/1bd66c704b379539c1e7425fdbaee1f911a8c148))
We've had a couple of places where it was assumed GetOwner() would always be valid. There should be proper checks everywhere now, even though in practice it should only come up when looking at other components such as the geometry brush.
