### ISSUE TITLE
One hand rotation not working

### ISSUE THREAD

**Issue by SuperFreqA** [microsoft/MixedReality-UXTools-Unreal#30]
I am running UE 4.26.1 and UXT 0,11
Creating an actor with a static mesh, a UxtGenericManipulator and a UxtBoundsControl results in the ability to rotate and scale using bounds control objects with one hand, but one hand translation and rotation without using the bounds control manipulators does not seem to work.

**Comment by SuperFreqA** [comment]
I am now using only the GenericManipulator and here is my configuration:
![image](https://user-images.githubusercontent.com/19316049/112380829-7a108300-8caf-11eb-90d5-292e974842c7.png)
The UXT demo game seems to work fine, so I must be missing something. I tried adding the Grab and Ungrab events to trigger debug and the event seems to be occurring, but not doing the action to translate or rotate. All settings on the GenericManipulator are default.
I also tried adding the grab events from the demo BP_Grabbable like this:
![image](https://user-images.githubusercontent.com/19316049/112381342-18044d80-8cb0-11eb-9dc1-19e9874f848c.png)
this did not change the behavior. 
I must be missing some important piece here.

**Comment by camccaf-msft** [comment]
Hey SuperFreqA! Can you check your UxtGenericManipulator's `One Hand Rotation Mode` setting? UXT 0.11 has the unfortunate default of setting this to `Maintain Original Rotation` which will prevent the object from rotating as you manipulate it. Setting this to `Rotate About Grab Point` should give you the expected behavior. Most of these flags have been replaced by a more flexible transform constraint system in the upcoming 0.12 release so this gotcha will no longer exist.

I haven't been able to reproduce the translation issue you mentioned, would you have a minimal repro project we could take a look at?

**Comment by SuperFreqA** [comment]
Setting the hand rotation mode didn't fix the problem unfortunately. I still see no translation or rotation of any kind coming through to the static mesh. 
Do I need to manually push the transform from the GenericManipulator to the static mesh? I don't recall having to do anything besides adding the component to my actor blueprint in 0.10. It feels like there is an update loop that is not happening.

**Comment by camccaf-msft** [comment]
You don't have to manually apply the transform, the component should function the same as it did in 0.10.
I've been able to replicate the behavior you're seeing by setting the `StaticMesh` and/or the `DefaultSceneRoot`'s _Mobility_ to _Static_ instead of _Movable_. Could this be what you're seeing here?

I've attached the project I've been using to try and repro this in-case that helps spot the difference with the setup you have in your project. To dig in further we will need more information about your specific project/actor settings or ideally an example project with this issue visible.
[UxtExample.zip](https://github.com/microsoft/MixedReality-UXTools-Unreal/files/6211295/UxtExample.zip)

**Comment by camccaf-msft** [comment]
Hey @SuperFreqA, any updates on if you have managed to get to the bottom of the issue you were seeing? If not we'd be happy to investigate further if you can provide the project+actor configuration / a sample repro project as mentioned above.

**Comment by luis-valverde-ms** [comment]
Closing this as it has been inactive for a while. @SuperFreqA feel free to re-open if your issue hasn't been solved. If you fixed it on your side, please do share the solution here so it can help others and maybe give us a hint about things that can be more clear. Thanks!
