### ISSUE TITLE
Hello, I made a blueprint. There is a static mesh in it. When the collision of the object is opened after a delay of 8 seconds, the object still can't be grasped.

### ISSUE THREAD

**Issue by YiRonger** [microsoft/MixedReality-UXTools-Unreal#35]
Hello, I made a blueprint. There is a static mesh in it. When the collision of the object is opened after a delay of 8 seconds, the object still can't be grasped.
![image](https://user-images.githubusercontent.com/46839641/128304843-5dc11405-8f96-45fe-97af-840f73c963e7.png)

**Comment by camccaf-msft** [comment]
Hey @YiRonger! The cube's initial collision configuration isn't visible in your screenshot but the most likely cause of this behavior is setting the **Collision Presets** property on the cube to _NoCollision_ instead of setting just the **Collision Enabled** property to _No Collision_.

The subtle difference here is that the _NoCollision_ preset disables visibility trace responses, which don't get re-enabled when using the **Set Collision Enabled** blueprint node. This is what prevents the manipulator from detecting the cube when you enable collision.

The fix for this is to set the cube's initial collision settings as follows:
![CollisionSettings](https://user-images.githubusercontent.com/54583751/128702349-76ed4478-a2da-49b5-b0b9-996c4e384530.png)

This way the traces are still enabled will start responding again when you call **Set Collision Enabled** from your blueprint.

**Comment by EVRTOP** [comment]
Hello, thank you very much. This problem has been solved.
 There is another problem. 
I tested the example of catching cheese. 
Why can I catch it before my hand touches the cheese?

**Comment by camccaf-msft** [comment]
This is actually expected behavior, we have a cone that extends out of the hand that triggers the change between near and far interaction modes and anything within this cone is considered close enough to be grabbed. You can see this cone using Unreal's [Visual Logger](https://docs.unrealengine.com/4.26/en-US/TestingAndOptimization/VisualLogger/). 
![VisualLogger](https://user-images.githubusercontent.com/54583751/128862189-8b95bb57-0adc-4381-a32f-e98f35311954.png)

This cone is configurable through the `Proximity Cone ...` properties on the **UxtHandInteractionActor**. Unfortunately these properties aren't exposed on spawn, to modify them you will have to place the **UxtHandInteractionActor**s in your scene manually instead of spawning them programmatically.
![ProximityConeConfig](https://user-images.githubusercontent.com/54583751/128862371-70f0d6bf-fb7a-462d-8951-f56235e09908.png).

**Comment by EVRTOP** [comment]
Oh, I understand. Thank you so much.

**Comment by EVRTOP** [comment]
Hello, one more question,

Now, an object is hidden and can still be caught.

How to make an object hidden without being caught and displayed before it can be caught?

**Comment by camccaf-msft** [comment]
No problem! That's another gotcha with Unreal where hiding an actor doesn't disable its collision volume. What you need to do is hide the actor and disable it's collision when you want it invisible and then re-enable both when you want it to be seen / caught again. This would be done using the **Set Actor Hidden In Game** and **Set Actor Enable Collision** blueprint nodes.

**Comment by YiRonger** [comment]
> No problem! That's another gotcha with Unreal where hiding an actor doesn't disable its collision volume. What you need to do is hide the actor and disable it's collision when you want it invisible and then re-enable both when you want it to be seen / caught again. This would be done using the **Set Actor Hidden In Game** and **Set Actor Enable Collision** blueprint nodes.

Oh, I see. Thank you very much!

**Comment by camccaf-msft** [comment]
No problem, I'll close this issue but feel free to create another if you hit any other bugs in UXTools!
