### ISSUE TITLE
Can't install packages from the MRTK Hub or GitHub

### ISSUE THREAD

**Issue by camccaf-havok** [microsoft/MixedReality-UXTools-Unreal#50]
Question from Ferrys93_de on the UE Marketplace:

> It is no problem to install the MRTK Hub. But when I try to install packages from it, nothing happens after the download is done. Sometimes a terminal window with red text pops up for about half a second, so I have no idea what it reads.
After that did not work, I downloaded the plugins from GitHub and put them into the "Plugins" folder. Starting the project UE4 asks me to add missing packages, after clicking "yes" it tells me that it could not compile, and I should do it manually.
Starting as Admin makes for both no differences.
Why does this error appear, and how can I fix it? 
Thanks in advance!

Need more information on:
* The Unreal Engine version being used?
* Is the project a Blueprint or C++ project?
* The Visual Studio version being used?
* The MRTK Hub version being used? (Found under Plugins -> Mixed Reality -> Mixed Reality Toolkit Hub)
* The Plugins (and versions) you're attempting to install?
* Which packages are being listed as missing in the "add missing packages" prompt?
* Can you attach the editor logs from the session where these issues occurred? (Found in the _ProjectName\Saved\Logs_ folder)

If you have a project that you can share with us that can demonstrate this issue, that would be a great help too!

**Comment by Ferrys93de** [comment]
Hello Mr. McCaffrey,

I linked a lot of screenshots and the log files from trying to install only the GT Tools via the Hub. I updated the UE4 from 27.1 to 27.2 and also checked all plugins for Visual Studio as well as my Windows and SDK version. Since I updated to 4.27.2 the error with the missing packages does not occur anymore. Further, was I not able to find the GT Tools I downloaded manually and put in the Plugins folder, maybe I did something wrong. I tried to follow your tutorial: https://www.youtube.com/watch?v=avTjzrv1jmc
If you need more information, just let me know.
Thanks

[Test4272Blue.log](https://github.com/microsoft/MixedReality-UXTools-Unreal/files/7685813/Test4272Blue.log)
[Test4272Blue_2.log](https://github.com/microsoft/MixedReality-UXTools-Unreal/files/7685814/Test4272Blue_2.log)
[Test4272Blue-backup-2021.12.09-14.08.11.log](https://github.com/microsoft/MixedReality-UXTools-Unreal/files/7685815/Test4272Blue-backup-2021.12.09-14.08.11.log)
![Options 11](https://user-images.githubusercontent.com/33072711/145415185-57a21ef4-d039-4241-a7be-4e4c7bcf4b51.png)
![Options 21](https://user-images.githubusercontent.com/33072711/145415220-b5bff710-277c-4270-b439-8e23ccd0c450.png)
![Packages](https://user-images.githubusercontent.com/33072711/145415225-44bd2da5-f61f-4a70-abcc-85fd875d044a.png)
![Plugins](https://user-images.githubusercontent.com/33072711/145415238-c106252d-9320-4c65-aff9-bbabe9bd8c91.png)
![Settings Blueprint](https://user-images.githubusercontent.com/33072711/145415242-aeed08b8-0b60-4253-ba56-a4ae67ca4320.png)
![Tresor](https://user-images.githubusercontent.com/33072711/145415257-7774a5d7-1a68-4d23-8c01-0d30a7c1fc38.png)
![Visual Studio Info](https://user-images.githubusercontent.com/33072711/145415262-41318cc4-cf65-45fd-bc2b-c918823dfa21.png)

**Comment by camccaf-havok** [comment]
Thanks for the info @Ferrysmc! Will look into this and report back with any findings

**Comment by LeoBensch** [comment]
> Thanks for the info @Ferrysmc! Will look into this and report back with any findings

Did you find any solution to solve this issue? I have the same problem when I try to follow the video tutorial

**Comment by camccaf-havok** [comment]
> > Thanks for the info @Ferrysmc! Will look into this and report back with any findings
> 
> Did you find any solution to solve this issue? I have the same problem when I try to follow the video tutorial

Sorry for the delay in responding here, the issue @Ferrysmc was hitting has been fixed in Hub version 1.0.2, which is now available on the Unreal Engine Marketplace. Let me know if you're hitting any other issues using the Hub!
